### PR TITLE
change to fifeengine msi installer and comment out demos and tools be…

### PR DESCRIPTION
**Pull request by LinuxDonald**
…cause we dont have in the installer yet.

@jakoch please review :)

### CODE REVIEW

**Comment by LinuxDonald** [comment]
@jakoch how can I clear the download cache one time?

**Comment by jakoch** [comment]
Edit the `appveyor.yml` file and add a new comment or something.

I've already prepared cache clearing, see first lines of `appveyor.yml`
```
# cache the "downloads" folder in the build folder
# refresh cache, if appveyor.yml changes
cache:
  - downloads -> appveyor.yml
```
Referencing: https://www.appveyor.com/docs/build-cache/#cleaning-up-cache

**Comment by LinuxDonald** [comment]
fife-sdk-installer-error

The fife installer could not execute. But when i go into the temp folder i can execute the fife installer without and problems.

**Comment by LinuxDonald** [comment]
Ah i found something:

`Filename: "msiexec.exe"; Parameters: "/i ""{tmp}\Your-MSI-File.msi"""`

http://www.jrsoftware.org/iskb.php?msi

**Comment by jakoch** [comment]
`msiexec` nice trick 👍 
The installer works for me. Good job.

**Comment by LinuxDonald** [comment]
Thank you :-) @jakoch could you maybe please squash and merge this pr please?

**Pull request merged**
